# Generated by Django 4.1.3 on 2022-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guestcanpause', models.BooleanField(default=False)),
                ('votestoskip', models.IntegerField(default=1)),
                ('created', models.DateField()),
            ],
        ),
    ]
